name = "Hugo Void"
license = "MIT"
licenselink = "https://github.com/f1rstf1nal/hugo-void/blob/master/LICENSE"
description = "A modern ultra-lightweight, responsive theme for Hugo full of features and built for blogs, portoflios, wikis and writeups"
homepage = "https://github.com/f1rstf1nal/hugo-void/"
tags = ['minimal', 'blog', 'sidebar']
features = []
min_version = "0.41.0"

[author]
  name = "Brett Final"
  homepage = "https://firstfinal.net/"